---
pause_print_job:
  target:
    entity:
      integration: chitubox_printer
      domain: sensor
      device_class: "3d-printer"

resume_print_job:
  target:
    entity:
      integration: chitubox_printer
      domain: sensor
      device_class: "3d-printer"

stop_print_job:
  target:
    entity:
      integration: chitubox_printer
      domain: sensor
      device_class: "3d-printer"

start_print_job:
  fields:
    filename:
      required: true
      example: "/usb/printme.ctb"
      selector:
        text:
    start_layer:
      default: 0
      selector:
        number:
          min: 0
  target:
    entity:
      integration: chitubox_printer
      domain: sensor
      device_class: "3d-printer"

turn_timelapse_off:
  target:
    entity:
      integration: chitubox_printer
      domain: sensor
      device_class: "3d-printer"

turn_timelapse_on:
  target:
    entity:
      integration: chitubox_printer
      domain: sensor
      device_class: "3d-printer"

turn_camera_off:
  target:
    entity:
      integration: chitubox_printer
      domain: sensor
      device_class: "3d-printer"

turn_camera_on:
  target:
    entity:
      integration: chitubox_printer
      domain: sensor
      device_class: "3d-printer"
