name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    name: HACS validation
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Validation
        uses: "hacs/action@main"
        with:
          category: "integration"

  validate-hass:
    name: Hassfest validation
    runs-on: "ubuntu-latest"
    steps:
        - name: Checkout
          uses: "actions/checkout@v4"
        - name: Validation
          uses: "home-assistant/actions/hassfest@master"